[package]
name = "blinky"
version = "0.1.0"
edition = "2018"

[dependencies]
feather_m4 = "0.4.0"
cortex-m = "0.6.2"
cortex-m-rt = "0.6.12"
panic-halt = "0.2.0"

[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = 'z'
