[package]
name = "blinky"
version = "0.1.0"
edition = "2018"

[profile.release]
opt-level = 'z'
lto = true
debug = true

[dependencies]
cortex-m = { version = "0.6.3", features = [ "const-fn" ] }
cortex-m-rt = "0.6.12"
embedded-hal = "0.2.4"
nrf52840-hal = "0.10.0"
panic-halt = "0.2.0"
