[package]
name = "blinky"
version = "0.1.0"
edition = "2018"

[dependencies]
xiao_m0 = "0.12.0"
cortex-m-rt = "0.7.2"
cortex-m = { version = "0.7.7", features = [ "inline-asm" ] }
panic-halt = "0.2.0"

[profile.release]
codegen-units = 1
debug = true
incremental = false
lto = true
opt-level = 'z'
